export const DELETE_PATIENT = 'Delete patient'
export const UPDATE_PATIENT = 'Update patient'
export const SET_PATIENTS = 'Set patients'
export const SET_PATIENTS_COUNT = 'Set patients count'
export const SET_PATIENT_DATA = 'Set current patient'
export const ADD_PATIENT_DATA = 'Add to current patient'
export const SET_MEDICATION = 'Set medication'
