export const DELETE_DOCTOR = 'Delete doctor'
export const SET_DOCTOR = 'Set doctor'
export const SET_DOCTORS = 'Set doctors'
export const SET_DOCTORS_COUNT = 'Set doctors count'
export const ADD_DOCTOR_DATA = 'Add doctor data'
