export const SET_RESOURCES = 'Set resources'
export const DELETE_RESOURCE = 'Delete resources'
export const UPDATE_RESOURCE = 'Update resources'
export const SET_SPECIALTIES = 'Set specialties'
export const SET_CATEGORIES = 'Set categories'
export const SET_CODES = 'Set codes'
