export default () => ({
  resources: [],
  specialties: [],
  categories: [],
  codes: [],
  serviceTypes: [],
  currentResource: {},
  paymentMethods: [],
  encounterClasses: [],
  maritalStatuses: [],
  medicationOptions: [],
  clinicalOptions: [],
  encounterStatuses: [],
  religiousAffiliations: [],
})
