export const DELETE_APPOINTMENT = 'Delete appointment'
export const SET_APPOINTMENT = 'Set appointment'
export const SET_APPOINTMENTS = 'Set appointments'
export const SET_APPOINTMENTS_COUNT = 'Set appointments count'
export const ADD_APPOINTMENT_DATA = 'Add appointment data'
